[node]
name = "helium-node"
rpc_bind = "0.0.0.0:20443"
#working_dir = "/tmp/stacks-blockchain-data"

[burnchain]
chain = "bitcoin"
mode = "mocknet"
commit_anchor_block_within = 10000

[[mstx_balance]]
address = "ST1WHW84WV9D67CQZV3NY5NM284GF9TXZ4CS7RDRF"
amount = 10000000000000000

[[mstx_balance]]
address = "ST2R464YCJEXD4WXR90XCEN5BKBFB7S37TZ207BSY"
amount = 10000000000000000

[[mstx_balance]]
address = "STRH5TEWEDRM14K4GWWF37FHDFC69ZKH90FMA6NF"
amount = 10000000000000000

[[mstx_balance]]
address = "ST1XDVK637SACQG1TMBVSXVW3GK5K35R82KNMN2QG"
amount = 10000000000000000
